apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foos.samplecontroller.k8s.io
spec:
  group: samplecontroller.k8s.io
  versions:
  - name: "v1"
    served: true
    storage: false
  - name: "v1alpha1"
    served: true
    storage: true
  conversion:
    strategy: None
  names:
    kind: Foo
    plural: foos
  scope: Namespaced
