apiVersion: v1
kind: Pod
metadata:
  name: example-conversion-webhook
  labels:
    app: webhook
spec:
  containers:
  - name: converter
    image: "gcr.io/kubernetes-e2e-test-images/crd-conversion-webhook:1.14rev4"
    args: ["--tls-cert-file=/var/certs/cert.pem", "--tls-private-key-file=/var/certs/key.pem", "--alsologtostderr", "-v=4", "2>&1"]
    ports:
      - containerPort: 9443
    volumeMounts:
    - mountPath: "/var/certs"
      name: certs
      readOnly: true
  volumes:
  - name: certs
    secret:
      secretName: webhook-tls-certs
