apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foos.stable.example.com
spec:
  group: stable.example.com
  versions:
  - name: "v1"
    served: true
    storage: false
  - name: "v2"
    served: true
    storage: true
  names:
    kind: Foo
    plural: foos
  scope: Namespaced
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          x-kubernetes-preserve-unknown-fields: true
        host:
          type: string
        port:
          type: string
        hostPort:
          type: string
      type: object
