apiVersion: v1
kind: Config
users:
- name: cr-scale-benchmark
  user:
    token: ${USER_TOKEN}
clusters:
- name: local
  cluster:
    insecure-skip-tls-verify: true
    server: https://localhost:443
contexts:
- context:
    cluster: local
    user: cr-scale-benchmark
  name: cr-scale-benchmark
current-context: cr-scale-benchmark
